<a href="https://colab.research.google.com/github/GlobalFishingWatch/gfw-api-python-client/blob/develop/notebooks/usage-guides/events-api.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Events API

This guide provides detailed instructions on how to use the [gfw-api-python-client](https://github.com/GlobalFishingWatch/gfw-api-python-client) to access information about various activities of a vessel, including fishing activity, encounters, port visits, loitering, and gaps in AIS reporting through the Global Fishing Watch [Events API](https://globalfishingwatch.org/our-apis/documentation#events-api).

**Note:** See the [Datasets](https://globalfishingwatch.org/our-apis/documentation#api-dataset), [Events Data Caveats](https://globalfishingwatch.org/our-apis/documentation#how-are-the-events-estimated), and [Terms of Use](https://globalfishingwatch.org/our-apis/documentation#terms-of-use) pages in the [GFW API documentation](https://globalfishingwatch.org/our-apis/documentation#introduction) for details on GFW data, API licenses, and rate limits.

## Prerequisites

Before using the `gfw-api-python-client`, ensure it is installed (see the [Getting Started](https://globalfishingwatch.github.io/gfw-api-python-client/getting-started.html) guide) and that you have obtained an API access token from the [Global Fishing Watch API portal](https://globalfishingwatch.org/our-apis/tokens).

## Installation

The `gfw-api-python-client` can be easily installed using pip:

In [1]:
# %pip install gfw-api-python-client

## Usage

Import and use `gfw-api-python-client` in your Python codes

In [2]:
import os

import gfwapiclient as gfw

In [3]:
try:
    from google.colab import userdata

    access_token = userdata.get("GFW_API_ACCESS_TOKEN")
except Exception:
    access_token = os.environ.get("GFW_API_ACCESS_TOKEN")

access_token = access_token or "<PASTE_YOUR_GFW_API_ACCESS_TOKEN_HERE>"

In [4]:
gfw_client = gfw.Client(
    access_token=access_token,
)

## Retrieving All Events (`get_all_events`)

In [5]:
events_result = await gfw_client.events.get_all_events(
    datasets=["public-global-fishing-events:latest"],
    start_date="2020-10-01",
    end_date="2020-12-31",
    region={
        "dataset": "public-eez-areas",
        "id": "8371",
    },
    limit=5,
)

### Access the list of event as Pydantic models

In [6]:
events_data = events_result.data()

In [7]:
event = events_data[-1]

In [8]:
event.id, event.type, event.vessel.id

('bbbf5d0cfa9639e5eac0130fc2b742e9',
 'fishing',
 '7374d1988-87f8-6037-66b4-59854a026efb')

### Access the events as a DataFrame

In [9]:
events_df = events_result.df()

In [10]:
events_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   start         5 non-null      datetime64[ns, UTC]
 1   end           5 non-null      datetime64[ns, UTC]
 2   id            5 non-null      object
 3   type          5 non-null      object
 4   position      5 non-null      object
 5   regions       5 non-null      object
 6   bounding_box  5 non-null      object
 7   distances     5 non-null      object
 8   vessel        5 non-null      object
 9   encounter     0 non-null      object
 10  fishing       5 non-null      object
 11  gap           0 non-null      object
 12  loitering     0 non-null      object
 13  port_visit    0 non-null      object
dtypes: datetime64[ns, UTC](2), object(12)
memory usage: 692.0+ bytes

In [11]:
events_df.head()

,start,end,id,type,position,regions,bounding_box,distances,vessel,encounter,fishing,gap,loitering,port_visit
0,2020-09-29 01:36:43+00:00,2020-10-01 06:21:11+00:00,a0f5848d1a83b7f0b4b8cda6873699ba,fishing,"{'lat': 14.6865, 'lon': -17.4115}","{'mpa': ['555705172'], 'eez': ['8371'], 'rfmo'...","[-17.4119, 14.686378333333334, -17.41116833333...","{'start_distance_from_shore_km': 2.0, 'end_dis...",{'id': '9e01144bf-f383-e634-3178-ca7e34477f34'...,None,"{'total_distance_km': 3.4650098660546633, 'ave...",None,None,None
1,2020-09-29 10:27:14+00:00,2020-10-01 06:16:35+00:00,670e2c0d5e1423f7d63821200a140d6f,fishing,"{'lat': 13.7439, 'lon': -17.0539}","{'mpa': ['555651502'], 'eez': ['8371'], 'rfmo'...","[-16.967778333333342, 13.59392, -17.25, 13.910...","{'start_distance_from_shore_km': 29.0, 'end_di...",{'id': '56797171d-dc16-997d-5765-61029b1e0244'...,None,"{'total_distance_km': 294.3073276985627, 'aver...",None,None,None
2,2020-09-30 07:13:23+00:00,2020-10-01 05:15:51+00:00,d1d52b881f7c22df0dc289534679d647,fishing,"{'lat': 14.3766, 'lon': -17.2489}","{'mpa': ['555705172'], 'eez': ['8371'], 'rfmo'...","[-17.331973333333334, 14.21384, -17.1248533333...","{'start_distance_from_shore_km': 40.0, 'end_di...",{'id': 'd29f3a946-6ece-2c04-7c5f-43dcc3515707'...,None,"{'total_distance_km': 130.6216027333083, 'aver...",None,None,None
3,2020-09-30 12:35:44+00:00,2020-10-01 07:11:05+00:00,cebc86436ee6fb3e792a49ced7840ea4,fishing,"{'lat': 15.501, 'lon': -17.2188}","{'mpa': [], 'eez': ['8371'], 'rfmo': ['SRFC', ...","[-17.1261683333, 15.2266266667, -17.3346466666...","{'start_distance_from_shore_km': 20.0, 'end_di...",{'id': '14fdac9e8-8a83-0d3b-0483-94e520ceaf80'...,None,"{'total_distance_km': 111.11378725724042, 'ave...",None,None,None
4,2020-09-30 13:18:27+00:00,2020-10-01 07:33:45+00:00,bbbf5d0cfa9639e5eac0130fc2b742e9,fishing,"{'lat': 14.9647, 'lon': -17.6039}","{'mpa': [], 'eez': ['8371'], 'rfmo': ['ACAP', ...","[-17.480231666700007, 14.8685916667, -17.67519...","{'start_distance_from_shore_km': 11.0, 'end_di...",{'id': '7374d1988-87f8-6037-66b4-59854a026efb'...,None,"{'total_distance_km': 93.2534926758473, 'avera...",None,None,None

## Retrieving a Single Event by ID (`get_event_by_id`)

In [12]:
event_result = await gfw_client.events.get_event_by_id(
    id="c2f0967e061f99a01793edac065de003",
    dataset="public-global-port-visits-events:latest",
)

### Access the event model as Pydantic model

In [13]:
event = event_result.data()

In [14]:
event.id, event.type, event.vessel.id

('c2f0967e061f99a01793edac065de003',
 'port_visit',
 '8c7304226-6c71-edbe-0b63-c246734b3c01')

### Access the event as a DataFrame

In [15]:
event_df = event_result.df()

In [16]:
event_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   start         1 non-null      datetime64[ns, UTC]
 1   end           1 non-null      datetime64[ns, UTC]
 2   id            1 non-null      object
 3   type          1 non-null      object
 4   position      1 non-null      object
 5   regions       1 non-null      object
 6   bounding_box  1 non-null      object
 7   distances     1 non-null      object
 8   vessel        1 non-null      object
 9   encounter     0 non-null      object
 10  fishing       0 non-null      object
 11  gap           0 non-null      object
 12  loitering     0 non-null      object
 13  port_visit    1 non-null      object
dtypes: datetime64[ns, UTC](2), object(12)
memory usage: 244.0+ bytes

In [17]:
event_df.head()

,start,end,id,type,position,regions,bounding_box,distances,vessel,encounter,fishing,gap,loitering,port_visit
0,2020-01-26 05:52:47+00:00,2020-01-29 14:39:33+00:00,c2f0967e061f99a01793edac065de003,port_visit,"{'lat': 20.7288, 'lon': -17.0148}","{'mpa': [], 'eez': ['8369'], 'rfmo': ['NAMMCO'...","[-17.014774393446658, 20.72879719687954, -17.0...","{'start_distance_from_shore_km': 7.0, 'end_dis...",{'id': '8c7304226-6c71-edbe-0b63-c246734b3c01'...,None,None,None,None,{'visit_id': '38affb3e7bdc67e9c0c2e7e8f3b08da2...

## Getting Event Statistics (`get_events_stats`)

In [18]:
event_stats_result = await gfw_client.events.get_events_stats(
    datasets=["public-global-encounters-events:latest"],
    encounter_types=["CARRIER-FISHING", "FISHING-CARRIER"],
    vessel_types=["CARRIER"],
    start_date="2018-01-01",
    end_date="2023-01-31",
    timeseries_interval="YEAR",
    flags=["RUS"],
    duration=60,
)

### Access the statistics as Pydantic models

In [19]:
event_stat = event_stats_result.data()

In [20]:
event_stat.num_events, event_stat.num_flags, event_stat.num_vessels

(24770, 1, 196)

### Access the statistics as a DataFrame

In [21]:
event_stat_df = event_stats_result.df()

In [22]:
event_stat_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   num_events   1 non-null      int64
 1   num_flags    1 non-null      int64
 2   num_vessels  1 non-null      int64
 3   flags        1 non-null      object
 4   timeseries   1 non-null      object
dtypes: int64(3), object(2)
memory usage: 172.0+ bytes

In [23]:
event_stat_df

,num_events,num_flags,num_vessels,flags,timeseries
0,24770,1,196,[RUS],"[{'date': 2018-01-01 00:00:00+00:00, 'value': ..."