<a href="https://colab.research.google.com/github/GlobalFishingWatch/gfw-api-python-client/blob/develop/notebooks/usage-guides/references-data-api.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Reference Data API

This guide provides detailed instructions on how to use the [gfw-api-python-client](https://github.com/GlobalFishingWatch/gfw-api-python-client) to access reference data, specifically geographic regions.

**Note:** See the [Datasets](https://globalfishingwatch.org/our-apis/documentation#api-dataset), [Reference Data Caveats](https://globalfishingwatch.org/our-apis/documentation#reference-data), and [Terms of Use](https://globalfishingwatch.org/our-apis/documentation#terms-of-use) pages in the [GFW API documentation](https://globalfishingwatch.org/our-apis/documentation#introduction) for details on GFW data, API licenses, and rate limits.

## Prerequisites

Before using the `gfw-api-python-client`, ensure it is installed (see the [Getting Started](https://globalfishingwatch.github.io/gfw-api-python-client/getting-started.html) guide) and that you have obtained an API access token from the [Global Fishing Watch API portal](https://globalfishingwatch.org/our-apis/tokens).

## Installation

The `gfw-api-python-client` can be easily installed using pip:

In [1]:
# %pip install gfw-api-python-client

## Usage

In [2]:
import os
import gfwapiclient as gfw

In [3]:
try:
    from google.colab import userdata

    access_token = userdata.get("GFW_API_ACCESS_TOKEN")
except Exception as exc:
    access_token = os.environ.get("GFW_API_ACCESS_TOKEN")

access_token = access_token or "<PASTE_YOUR_GFW_API_ACCESS_TOKEN_HERE>"

In [4]:
gfw_client = gfw.Client(
    access_token=access_token,
)

## Retrieving Exclusive Economic Zones (EEZs)

In [5]:
eez_regions_result = await gfw_client.references.get_eez_regions()

### Access the list of EEZ region as Pydantic models

In [6]:
eez_regions_data = eez_regions_result.data()

In [7]:
eez_region = eez_regions_data[-1]

In [8]:
eez_region.id, eez_region.dataset, eez_region.iso3

(48999, 'public-eez-areas', None)

### Access the EEZ regions as a DataFrame

In [9]:
eez_regions_df = eez_regions_result.df()

In [10]:
eez_regions_df[["id", "label", "iso3", "dataset"]].head()

,id,label,iso3,dataset
0,8491,Jordanian Exclusive Economic Zone,None,public-eez-areas
1,8467,Uruguayan Exclusive Economic Zone,None,public-eez-areas
2,5683,Latvian Exclusive Economic Zone,None,public-eez-areas
3,48950,Overlapping claim Kuril Islands: Japan / Russia,None,public-eez-areas
4,8327,South Korean Exclusive Economic Zone,None,public-eez-areas

## Retrieving Marine Protected Areas (MPAs)

In [11]:
mpa_regions_result = await gfw_client.references.get_mpa_regions()

### Access the list of MPA region Pydantic models

In [12]:
mpa_regions_data = mpa_regions_result.data()

In [13]:
mpa_region = mpa_regions_data[-1]

In [14]:
mpa_region.id, mpa_region.dataset

('555790807', 'public-mpa-all')

### Access the MPA regions as a DataFrame

In [15]:
mpa_regions_df = mpa_regions_result.df()

In [16]:
mpa_regions_df.head()

   id                                              label  name         dataset
0   1  Diamond Reef and Salt Fish Tail Reef - Marine ...  None  public-mpa-all
1   2                     Palaster Reef - Marine Reserve  None  public-mpa-all
2  27                         Folkstone - Marine Reserve  None  public-mpa-all
3  46  Reserva Biológica Atol Das Rocas - Reserva Bio...  None  public-mpa-all
4  57            Parque Nacional Do Cabo Orange - Parque  None  public-mpa-all

## Retrieving Regional Fisheries Management Organizations (RFMOs)

In [17]:
rfmo_regions_result = await gfw_client.references.get_rfmo_regions()

### Access the list of RFMO region as Pydantic models

In [18]:
rfmo_regions_data = rfmo_regions_result.data()

In [19]:
rfmo_region = rfmo_regions_data[-1]

In [20]:
rfmo_region.id, rfmo_region.dataset

('BOBP-IGO', 'public-rfmo')

### Access the RFMO regions as a DataFrame

In [21]:
rfmo_regions_df = rfmo_regions_result.df()

In [22]:
rfmo_regions_df.head()

        id    label   rfb      dataset       ID
0      LTA      LTA  None  public-rfmo      LTA
1  SEAFDEC  SEAFDEC  None  public-rfmo  SEAFDEC
2    IATTC    IATTC  None  public-rfmo    IATTC
3    APFIC    APFIC  None  public-rfmo    APFIC
4     IPHC     IPHC  None  public-rfmo     IPHC