<a href="https://colab.research.google.com/github/GlobalFishingWatch/gfw-api-python-client/blob/develop/notebooks/usage-guides/vessels-api.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Vessels API

This guide provides detailed instructions on how to use the  [gfw-api-python-client](https://github.com/GlobalFishingWatch/gfw-api-python-client) to access information about vessels.

**Note:** See the [Datasets](https://globalfishingwatch.org/our-apis/documentation#api-dataset), [Vessel Data Caveats](https://globalfishingwatch.org/our-apis/documentation#vessel-api-vessel-identity-information), and [Terms of Use](https://globalfishingwatch.org/our-apis/documentation#terms-of-use) pages in the [GFW API documentation](https://globalfishingwatch.org/our-apis/documentation#introduction) for details on GFW data, API licenses, and rate limits.

## Prerequisites

Before using the `gfw-api-python-client`, you need to obtain an API access token from the [Global Fishing Watch API portal](https://globalfishingwatch.org/our-apis/tokens)

## Installation

The `gfw-api-python-client` can be easily installed using pip:

In [1]:
# %pip install gfw-api-python-client

## Usage

In [2]:
import os
import gfwapiclient as gfw

In [3]:
try:
    from google.colab import userdata

    access_token = userdata.get("GFW_API_ACCESS_TOKEN")
except Exception as exc:
    access_token = os.environ.get("GFW_API_ACCESS_TOKEN")

access_token = access_token or "<PASTE_YOUR_GFW_API_ACCESS_TOKEN_HERE>"

In [4]:
gfw_client = gfw.Client(
    access_token=access_token,
)

## Searching for Vessels (`search_vessels`)

In [5]:
vessel_search_result = await gfw_client.vessels.search_vessels(
    where="ssvid='775998121' AND shipname='DON TITO'",
    datasets=["public-global-vessel-identity:latest"],
    includes=["MATCH_CRITERIA", "OWNERSHIP"],
)

### Access the list of vessel as Pydantic models

In [6]:
vessel_search_data = vessel_search_result.data()

In [7]:
vessel = vessel_search_data[-1]

In [8]:
vessel.dataset, vessel.self_reported_info[-1].id

('public-global-vessel-identity:v3.0', 'bae8f325c-cf0a-01fe-6d1a-9a275588d4ff')

### Access the vessels as a DataFrame

In [9]:
vessel_search_df = vessel_search_result.df()

In [10]:
vessel_search_df.head()

,dataset,registry_info_total_records,registry_info,registry_owners,registry_public_authorizations,combined_sources_info,self_reported_info,matchCriteria
0,public-global-vessel-identity:v3.0,0,[],[],None,[{'vessel_id': 'c54923e64-46f3-9338-9dcb-ff097...,[{'id': 'c54923e64-46f3-9338-9dcb-ff09724077a3...,[{'reference': 'c54923e64-46f3-9338-9dcb-ff097...
1,public-global-vessel-identity:v3.0,0,[],[],None,[{'vessel_id': 'bae8f325c-cf0a-01fe-6d1a-9a275...,[{'id': 'bae8f325c-cf0a-01fe-6d1a-9a275588d4ff...,[{'reference': 'bae8f325c-cf0a-01fe-6d1a-9a275...

## Getting a List of Vessels by IDs (`get_vessels_by_ids`)

In [11]:
vessels_result = await gfw_client.vessels.get_vessels_by_ids(
    ids=[
        "8c7304226-6c71-edbe-0b63-c246734b3c01",
        "6583c51e3-3626-5638-866a-f47c3bc7ef7c",
        "71e7da672-2451-17da-b239-857831602eca",
    ],
    datasets=["public-global-vessel-identity:latest"],
)

### Access the list of vessel as Pydantic models

In [12]:
vessels_data = vessels_result.data()

In [13]:
vessel = vessels_data[-1]

In [14]:
vessel.dataset, vessel.self_reported_info[-1].id

('public-global-vessel-identity:v3.0', 'aca119c29-95dd-f5c4-2057-ee45268dcd6f')

### Access the vessels as a DataFrame

In [15]:
vessel_search_df = vessels_result.df()

In [16]:
vessel_search_df.head()

,dataset,registry_info_total_records,registry_info,registry_owners,registry_public_authorizations,combined_sources_info,self_reported_info
0,public-global-vessel-identity:v3.0,1,"[{'id': '685862e0626f6234c844919bc738a83a', 's...",[],"[{'date_from': 2012-01-01 00:00:00+00:00, 'dat...",[{'vessel_id': '55889aefb-bef9-224c-d2db-58ecd...,[{'id': '71e7da672-2451-17da-b239-857831602eca...
1,public-global-vessel-identity:v3.0,2,"[{'id': 'a8d00ce54b37add7f85a35fcce8e7a1b', 's...",[],"[{'date_from': 2023-01-01 00:00:00+00:00, 'dat...",[{'vessel_id': '3c81a942b-bf0a-f476-ea72-75c02...,[{'id': 'da1cd7e1b-b8d0-539c-6581-2b3df8d0a6af...
2,public-global-vessel-identity:v3.0,2,"[{'id': 'b82d02e5c2c11e5fe5367c91194fc3ba', 's...",[],"[{'date_from': 2015-10-08 00:00:00+00:00, 'dat...",[{'vessel_id': 'aca119c29-95dd-f5c4-2057-ee452...,[{'id': '6583c51e3-3626-5638-866a-f47c3bc7ef7c...

## Getting a Vessel by ID (`get_vessel_by_id`)

In [17]:
vessel_result = await gfw_client.vessels.get_vessel_by_id(
    id="c54923e64-46f3-9338-9dcb-ff09724077a3",
    dataset="public-global-vessel-identity:latest",
)

### Access the vessel as Pydantic model

In [18]:
vessel = vessel_result.data()

In [19]:
vessel.dataset, vessel.self_reported_info[-1].id

('public-global-vessel-identity:v3.0', 'c54923e64-46f3-9338-9dcb-ff09724077a3')

### Access the vessel as a DataFrame

In [20]:
vessel_df = vessel_result.df()

In [21]:
vessel_df.head()

,dataset,registry_info_total_records,registry_info,registry_owners,registry_public_authorizations,combined_sources_info,self_reported_info
0,public-global-vessel-identity:v3.0,0,[],[],[],[{'vessel_id': 'c54923e64-46f3-9338-9dcb-ff097...,[{'id': 'c54923e64-46f3-9338-9dcb-ff09724077a3...